Typescript
kphutiyagae/flight-tracking-app pull request #5
Opened 2023-03-03 13:10 UTC by kphutiyagae

* Converted JS files to TS.
* Added Interfaces.
* Merged Develop into Typescript feature branch.

2023-03-03 13:32 UTC, sechaba-mache requested changes
Add whole dist folder to gitignore

2023-03-03 13:32 UTC, sechaba-mache commented on src/scripts/api-observables.ts
> +const flightDataObservable$ = new Observable((subscriber) => subscriber.next());
No type specified for flightDataObservable$

2023-03-03 13:32 UTC, sechaba-mache commented on src/scripts/map-service.ts
> +const mapObserver = {
Add typing for mapObserver

2023-03-03 13:32 UTC, sechaba-mache commented on src/scripts/observables.ts
> +const cachedOrRequestedFlightData$ = iif(
Add typing

2023-03-03 13:32 UTC, sechaba-mache commented on src/types/interfaces.d.ts
> +export interface ofError {
Bad naming on interface. Start with capital I then name

2023-03-03 13:34 UTC, kphutiyagae commented on src/types/interfaces.d.ts
> +export interface ofError {
Resolved.

2023-03-05 17:13 UTC, sechaba-mache approved these changes

2023-03-05 17:20 UTC, kphutiyagae commented
* Changed Javascript implementation to Typescript.

2023-03-05 17:22 UTC, merged